server:
  port: 9092

# 消费者的模式一般不用配置数据库,此处主要是针对Command模式下,命令的回call
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/eventuate
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

eventuatelocal:
  rocket:
    mq:
      nameserver:
        address: 127.0.0.1:9876

# 消费者模式下主要配置从Kafka读取数据
#eventuatelocal:
#  kafka:
#    bootstrap:
#      servers: 127.0.0.1:9092
#  zookeeper:
#    connection:
#      string: 127.0.0.1:2181